services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lume_server
      POSTGRES_PASSWORD: "AOkx_8Kz_AudayuGCa1VAR-bLeAF7Xvx"
    volumes:
      - lume_server_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "w6YtcrO7JZo7Mx3NTP22ezbYF4ZD9h-O"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lume_server_test
      POSTGRES_PASSWORD: "EnvkEL834jYhSKbP8Jg-C02YDMFl5FJf"
    volumes:
      - lume_server_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "uUeDiShoKo5N98vJXBqgkLB5ZidsSBul"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  lume_server_data:
  lume_server_test_data:
